server:
  port: 8080
  servlet:
    context-path: /mutant

spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:testdb;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: